sentry:
    dsn: "%env(SENTRY_DSN)%"
    register_error_listener: false
    options:
        traces_sample_rate: 0.1

monolog:
    handlers:
        sentry:
            type: sentry
            hub_id: Sentry\State\HubInterface
